version: "3.9"
services:
  bank-service:
    depends_on:
      docker-mysql:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"
      - "8787:8787"
  docker-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306